# Generated by Django 5.0 on 2023-12-18 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.post.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("post", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=apps.post.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="genres", to="post.genre"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="post.tag"
            ),
        ),
    ]
