# Generated by Django 5.0 on 2023-12-20 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="name",
            new_name="chapter_count",
        ),
    ]
