# Generated by Django 5.0 on 2023-12-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="age_limit",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("6+", "6+"),
                    ("12+", "12+"),
                    ("16+", "16+"),
                    ("18+", "18+"),
                ],
                db_index=True,
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("черновик", "Черновик"),
                    ("опубликовано", "Опибликовано"),
                    ("заморожено", "Заморожено"),
                    ("анонс", "Анонс"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("манга", "Манга"),
                    ("манхва", "Манхва"),
                    ("маньхуа", "Маньхуа"),
                    ("западный комикс", "Западный комикс"),
                    ("рукомикс", "Рукомикс"),
                    ("индонезийский комикс", "Индонезийский комикс"),
                    ("другое", "Другое"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
