# Generated by Django 5.0 on 2023-12-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_rename_name_chapter_chapter_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Status", "verbose_name_plural": "Status"},
        ),
        migrations.AlterField(
            model_name="chapter",
            name="chapter_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
