# Generated by Django 5.0 on 2023-12-26 01:22

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_post_age_limit_alter_post_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=255,
                populate_from=["rus_name", "pk"],
                unique=True,
            ),
        ),
    ]
