# Generated by Django 5.0 on 2023-12-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_status_options_alter_chapter_chapter_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="age_limit",
            field=models.CharField(
                choices=[(0, "All"), (6, "6+"), (12, "12+"), (16, "16+"), (18, "18+")],
                max_length=7,
            ),
        ),
    ]
