# Generated by Django 5.0 on 2023-12-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_alter_post_age_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="age_limit",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("6+", "6+"),
                    ("12+", "12+"),
                    ("16+", "16+"),
                    ("18+", "18+"),
                ],
                max_length=7,
            ),
        ),
    ]
