# Generated by Django 5.0 on 2023-12-20 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_alter_post_age_limit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="chapter_count",
            new_name="chapter_number",
        ),
    ]
